### ISSUE TITLE
Typos in README for CLPFUDatabase package

### ISSUE THREAD

**Issue by MatthewHeun** [EnergyEconomyDecoupling/CL-PFU-JOSS-Paper#14]
In Issue #5, @nmstreethran wrote

There are a couple of typos in the Statement of need in the README of https://github.com/EnergyEconomyDecoupling/CLPFUDatabase (CLPFUDatbase)

**Comment by MatthewHeun** [comment]
@nmstreethran, thanks for this comment.

I ran the `README.Rmd` and `README.md` through two spell checks (RStudio and MS Word). I didn't find any typos.

Are you flagging "exergy" as a typo? Exergy is a work different quantification of energy and the subject of the database. So that is not a typo.

I'm closing this issue because I couldn't find a typo. But I invite you to reopen the issue and point out any typos that I missed.

**Comment by nmstreethran** [comment]
Sorry, I should have been clearer. The typos are in the name of the metapackage in the final paragraph of the Statement of need (it says **CLPFUDatbase**):

[This package (`CLPFUDatbase`) addresses the need for a simple way to
install all dependencies. `CLPFUDatbase` is metapackage[^1], whose](https://github.com/EnergyEconomyDecoupling/CLPFUDatabase/blob/6a98fe56447479e0f132be3eb70a4df798dac5c0/README.md?plain=1#L42-L43)

**Comment by MatthewHeun** [comment]
@nmstreethran, thanks for clarifying! That's a tough one to see.

Anyway, the typo is now fixed, so I'm closing this issue.
