### ISSUE TITLE
Add link from paper to CLPFUDatabase repo 

### ISSUE THREAD

**Issue by MatthewHeun** [EnergyEconomyDecoupling/CL-PFU-JOSS-Paper#15]
In #5, @nmstreethran wrote:

I think it would be good if you can add a link to the CLPFUDatabase GitHub repo in the README of https://github.com/EnergyEconomyDecoupling/CL-PFU-JOSS-Paper

**Comment by MatthewHeun** [comment]
@nmstreethran:

Thanks for this suggestion! I added links to the GitHub repo in two places

- The second paragraph
- The table of GitHub packages

Further, I added a citation with the DOI to trigger citation databases.

**Comment by nmstreethran** [comment]
Thank you, I was actually referring to the README of this repository, as it currently lists all the dependencies and their links but doesn't have a link to the metapackage's repo. Sorry about the confusion!

**Comment by MatthewHeun** [comment]
This has been solved with previous commit.
