### ISSUE TITLE
Add a command to install CL-PFU suite in documentation

### ISSUE THREAD

**Issue by MatthewHeun** [EnergyEconomyDecoupling/CL-PFU-JOSS-Paper#5]
@nmstreethran provided this comment in #1:

I think it would be great if you can include the command to install the entire suite in the documentation. I used the following command to install all dependencies. I also added the MatthewHeun/MKHthemes package as I encountered the following error during installation: ERROR: dependency ‘MKHthemes’ is not available for package ‘PFUDatabase’.

```
# install devtools if not already installed
# install.packages("devtools")

# install GitHub packages
devtools::install_github(c("MatthewHeun/IEATools",
                           "EnergyEconomyDecoupling/MWTools",
                           "MatthewHeun/Recca",
                           "EnergyEconomyDecoupling/PFUSetup",
                           "EnergyEconomyDecoupling/PFUPipelineTools",
                           "MatthewHeun/MKHthemes",
                           "EnergyEconomyDecoupling/PFUDatabase",
                           "EnergyEconomyDecoupling/PFUAggDatabase"))
```

**Comment by MatthewHeun** [comment]
@nmstreethran, thanks for this suggestion. Another way to achieve the same outcome would be to create a metapackage called, say, `CLPFUDatabase`. When one would say `install.package("CLPFUDatabase")`, all dependent packages would be installed. What do you think of that approach? If we went in that direction, I would probably rename 

- `PFUDatabase` --> `PFUPipeline` and
- `PFUAggDatabase` to `PFUAggPipeline`.
 
Another benefit of this approach is that we could easily address #2 with a `readme` file for the `CLPFUDatabase` metapackage.

Let me know what you think.

**Comment by nmstreethran** [comment]
Hi @MatthewHeun, that sounds like a great approach to me. A metapackage would simplify the installation process and can also easily satisfy the documentation requirement as you mentioned.

**Comment by MatthewHeun** [comment]
@nmstreethran: Thanks for your response. My team and I will explore the metapackage approach in the coming days. We will rename the packages, too. I think this will provide a nice solution for everyone.

**Comment by MatthewHeun** [comment]
@nmstreethran: Thanks for you excellent suggestion to create a simple way to install all dependencies for creating the CL-PFU database.

In response, I have created a metapackage called `CLPFUDatabase`, which itself depends on all packages required to create the database. When one installs the `CLPFUDatabase` package, all dependencies should also be installed. Would you be willing to test it? If so, first remove all relevant packages.

```
  remove.packages(c("CLPFUDatabase",
                    "MWTools",
                    "PFUAggPipeline",
                    "PFUPipeline",
                    "PFUPipelineTools",
                    "PFUSetup",
                    "IEATools",
                    "matsbyname",
                    "matsindf",
                    "MKHthemes",
                    "Recca",
                    "RCLabels"))
```

Then, try 

```
devtools::install_github("EnergyEconomyDecoupling/CLPFUDatabase")
```

You should see several messages indicating packages are installing.

I'm encountering one issue: I reach the GitHub API limits. I have an GitHub PAT, but the PAT doesn't seem to relieve the API limit. Please let me know what you experience.

**Comment by nmstreethran** [comment]
Hi @MatthewHeun, that's great! 

I just did a quick test. You have renamed two of the dependencies in https://github.com/EnergyEconomyDecoupling/CL-PFU-JOSS-Paper/issues/13 but it looks like the metapackage is still using their old names. I see that you have changed them in the `develop` branch but haven't merged them into `main` yet.

So I tried `devtools::install_github("EnergyEconomyDecoupling/CLPFUDatabase", ref = "develop")` instead and encountered the GitHub API limit issue you mentioned. I tried to set up a GitHub PAT but as you said this did not seem to help (I still had a rate limit of 60). I waited for my rate limit to reset and ran the installation command again and the metapackage installed successfully this time!

I'll also test the example tomorrow.

**Comment by MatthewHeun** [comment]
@nmstreethran: That all sounds good. Good to find the develop branch!

I just released a new version of the `CLPUFDatabase` package, so the minor issue you encountered should be solved.

I will be releasing a new version of most packages in the next day, too, mostly to get the statements of need onto main/master branches.

Let me know how the example works! And thanks again for your good work on this review. I really appreciate it.

**Comment by nmstreethran** [comment]
@MatthewHeun thanks, I can confirm that it's resolved now.

My GitHub PAT also seems to be working now (I set `GITHUB_PAT` in the `.Renviron` file; `gitcreds::gitcreds_set()` didn't work for me).

I did run into another minor issue while running the example. See my comment in https://github.com/EnergyEconomyDecoupling/CL-PFU-JOSS-Paper/issues/8#issuecomment-1866130980.

Minor comments:
- There are a couple of typos in the Statement of need in the README of https://github.com/EnergyEconomyDecoupling/CLPFUDatabase (CLPFUDatbase)
- I think it would be good if you can add a link to the CLPFUDatabase GitHub repo in the README of https://github.com/EnergyEconomyDecoupling/CL-PFU-JOSS-Paper

**Comment by MatthewHeun** [comment]
@nmstreethran Thanks for confirming that the example is working for you now. Which implies that the command to install the suite of packages is also working (the original purpose of this issue). So I will close this issue now. I will open two new issues, one for each minor comment above.
