### ISSUE TITLE
Missing "i"

### ISSUE THREAD

**Issue by MatthewHeun** [EnergyEconomyDecoupling/CL-PFU-JOSS-Paper#6]
@nmstreethran provided this comment in #1:

The ℹ in the example code (line 108 in the PDF) seems to be missing.

**Comment by MatthewHeun** [comment]
@nmstreethran thanks for identifying this problem!

I also see this issue:

<img width="628" alt="image" src="https://github.com/EnergyEconomyDecoupling/CL-PFU-JOSS-Paper/assets/3308246/aa875f31-29d8-4332-adf6-e180a553f797">

The process to build the paper goes like this:

- Knit `paper.Rmd` to `paper.md` in RStudio
- Push the `paper.md` file to GitHub
- The GitHub action converts `paper.md` into `paper.pdf`

Interestingly, I see the "i" in `paper.md` at line 403:

<img width="562" alt="image" src="https://github.com/EnergyEconomyDecoupling/CL-PFU-JOSS-Paper/assets/3308246/d829148b-e64e-410c-a261-bcd2f0ca6ba1">

So the "i" is lost when the GitHub action creates `paper.pdf`.

Maybe @timtroendle can help us understand why the "i" is lost when the GitHub action creates the .pdf file?

**Comment by timtroendle** [comment]
Honestly, I do not know, sorry. Apparently, one of the dependencies in the build process cannot handle the special character. I am assuming you are using it as an abbreviation for "information"? Maybe the most pragmatic solution would be to avoid the abbreviation?

**Comment by MatthewHeun** [comment]
Thanks, @timtroendle. I checked, and the "i" appears correctly when building the paper locally, too, as shown in this screen shot:

<img width="648" alt="image" src="https://github.com/EnergyEconomyDecoupling/CL-PFU-JOSS-Paper/assets/3308246/1abdf9b5-6a22-47f6-ab72-590cee8369f8">

Digging further, the "i" (information character) comes from the `tibble` package, not from our code. Although we don't control the code that prints the "i", we can wrap the `psut` reference in `as.data.frame()`, so that `tibble` is no longer responsible for printing the data frame. This approach avoids the unprintable "i" altogether (even if the output isn't as compact or attractive), as shown in the following screen shot:

<img width="523" alt="image" src="https://github.com/EnergyEconomyDecoupling/CL-PFU-JOSS-Paper/assets/3308246/a51fea10-5813-45d3-a806-404eb0121e3e">

So it is pretty clear that the GitHub action that creates the .pdf is unable to handle the information "i" character. Perhaps you can provide some friendly feedback to the people responsible for the GitHub action at JOSS? Our paper can't be the only one that uses `tibble`s. I'll be happy to test a new version of the GitHub action, if one is created.

For now, I edited the paper to avoid the unprintable "i" character and am closing this issue.
