### ISSUE TITLE
Example doesn't work for @nmstreethran

### ISSUE THREAD

**Issue by MatthewHeun** [EnergyEconomyDecoupling/CL-PFU-JOSS-Paper#8]
@nmstreethran wrote the following in #1:

I tried running the example but ran into a few issues. I couldn't run (2) without installing FAOSTAT and Rilostat. I also had to install future.callr to run (3). Should these be part of the dependencies? I also ran into this error when running the PFUDatabase pipeline in (3) and got stuck there. Any idea why this is happening?

**Comment by MatthewHeun** [comment]
I added `FAOSTAT` and `Rilostat` to the `Suggests:` field in `MWTools`. I added `future.callr` to the `Suggests:` field in `PFUDatabase` and `PFUAggDatabase`.

I'm still working on the error. I am able to repeat it. It may be caused by a format change in the downloaded FAO data.

**Comment by MatthewHeun** [comment]
@nmstreethran: The example is now working for me. The problem was, indeed, a change in FAO data format.

But don't yet try it yourself. I have a couple things to double-check in `MWTools` package. And I need to do releases of some packages.

**Comment by MatthewHeun** [comment]
@nmstreethran: Thanks for identifying the problem with the example in the paper. 

In response, we have fixed the example by adjusting the `MWTools` package to respond to changes in the FAO data. Interestingly, the problem was caused by an FAO change in unit strings. Previously, the number of working animals was provided in units of "Head". The new format has units of "An", meaning "Animals", presumably. We were testing for "Head", because the FAO also previously used a unit of "1000 Head". We did not anticipate the change from "Head" to "An". (How could we? 🙂)

If you have the time, I would appreciate you trying the example in the paper again. 

The example now uses the metapackage (`CLPFUDatabase`). I requested a test of the `CLPFUDatabase` metapackage in #5, too. Hopefully, these two tests will not take too much time. If successful, I'll ping @timtroendle to say that all issues identified by the reviewers have been addressed.

We appreciate the effort you are taking to provide a thorough review!

**Comment by nmstreethran** [comment]
@MatthewHeun Many thanks for addressing my comments! I just tested the example and am happy to let you know that I was able to reproduce it. I did have issues with the `Suggests` packages not being installed though. I tried:

```r
devtools::install_github("EnergyEconomyDecoupling/CLPFUDatabase", dependencies = TRUE)
```

but I think this only installs the `Suggests` packages if they are in the `Suggests:` field of `CLPFUDatabase`?

So I still had to manually install `FAOSTAT`, `Rilostat`, and `future.callr` to proceed.

Minor comment: Since you've added `library(devtools)` to the example, I think you can remove `devtools::` from the `install_github` command in (0).

**Comment by MatthewHeun** [comment]
@nmstreethran: Thanks for doing the testing! 

My co-author @zekemarshall found that the GitHub API limit can be exceeded when you quote the `GITHUB_PAT` variable in `.Renviron` file like this:

`GITHUB_PAT = "ghp_XXXXXXXXX"`

So maybe give that a try. It works for me.

Furthermore, in response to your comments, I have:

- Added `FAOSTAT`, `future.callr`, and `Rilostat` to the dependences of `CLPFUDatabase`. Great catch!
- Removed `library(devtools)` from the example. I prefer the syntax `devtools::install_github()`, because it specifies the package at the point of the function call. 

When I
```r
  remove.packages(c("FAOSTAT",
                    "future.callr",
                    "Rilostat",
                    "RCLabels",
                    "matsbyname",
                    "matsindf",
                    "MKHthemes",
                    "MWTools",
                    "IEATools",
                    "Recca",
                    "PFUSetup",
                    "PFUPipelineTools",
                    "PFUPipeline",
                    "PFUAggPipeline",
                    "CLPFUDatabase"))
```
and thereafter run the example, everything works great.

So at this point, I'm closing this issue. If something doesn't work for you, I'll be happy to reopen it.
